-- 015_centre_scope_and_modules.sql
-- =====================================================================================
-- PURPOSE (ERP task A4.5 — second permission dimension: centre scope + more modules).
--   1. Widens the role_grants module vocabulary to 9 keys (adds 'inventory','reports')
--      so those modules can hold grants when their content ships. NO new grant rows
--      are seeded here — grants arrive with the content.
--   2. Adds a CENTRE SCOPE dimension to volunteers: `scope` (all_centers | own_center,
--      default own_center = fail-closed) + a nullable `centre_id`. Today's roles are
--      backfilled to all_centers (admin/erp_admin/committee); care volunteers keep the
--      default own_center + null centre — inert for them since they hold no ERP grants.
--   3. Adds public.centre_scope_allows(centre_id) and composes it into the member-data
--      RLS policies: every centre-owned read = has_module_access(module,'view') AND
--      centre_scope_allows(<row's centre_id>). This changes NOTHING for today's roles
--      (all all_centers; volunteer has no members grant) — it exists so Phase D centre
--      roles inherit a proven pattern rather than a retrofit.
--
--   THE PATTERN (for every future centre-owned table — finance/duty/inventory, Phase D+):
--   the table carries an explicit centre_id column, and its SELECT policy composes
--   `public.has_module_access('<module>','view') AND public.centre_scope_allows(centre_id)`.
--   Reference data (centres, teams) and the audit trail stay module-gated only.
--
-- APPLY MANUALLY (Supabase SQL Editor). Run docs/erp/04-a45-verification.md PREFLIGHT
--   first; STOP on any deviation.
--
-- ROLLBACK (manual):
--   -- restore the 5 member-data policies to their 014 (module-only) form:
--   drop policy if exists "members module can read members"        on public.members;
--   create policy "members module can read members" on public.members
--     for select to authenticated using (public.has_module_access('members','view'));
--   drop policy if exists "members module can read member_teams"   on public.member_teams;
--   create policy "members module can read member_teams" on public.member_teams
--     for select to authenticated using (public.has_module_access('members','view'));
--   drop policy if exists "members module can read member_skills"  on public.member_skills;
--   create policy "members module can read member_skills" on public.member_skills
--     for select to authenticated using (public.has_module_access('members','view'));
--   drop policy if exists "members module can read legacy_rows"    on public.legacy_rows;
--   create policy "members module can read legacy_rows" on public.legacy_rows
--     for select to authenticated using (public.has_module_access('members','view'));
--   drop policy if exists "members module can read import_batches" on public.import_batches;
--   create policy "members module can read import_batches" on public.import_batches
--     for select to authenticated using (public.has_module_access('members','view'));
--   -- drop the scope function + volunteer columns:
--   drop function if exists public.centre_scope_allows(uuid);
--   alter table public.volunteers drop column if exists scope;
--   alter table public.volunteers drop column if exists centre_id;
--   -- restore the 7-module CHECK (name will differ from the original autogenerated one):
--   alter table public.role_grants drop constraint if exists role_grants_module_check;
--   alter table public.role_grants add constraint role_grants_module_check
--     check (module in ('care','members','events','finance','duty','settings','audit'));
-- =====================================================================================


-- ── (a) widen the role_grants module vocabulary to 9 keys ────────────────────────────
-- The 014 module CHECK is autogenerated; drop it dynamically, then add a named one.
do $$
declare
  c_name text;
begin
  select conname
    into c_name
    from pg_constraint
   where conrelid = 'public.role_grants'::regclass
     and contype  = 'c'
     and pg_get_constraintdef(oid) ilike '%module%'
   limit 1;

  if c_name is not null then
    execute format('alter table public.role_grants drop constraint %I', c_name);
  end if;
end $$;

alter table public.role_grants
  add constraint role_grants_module_check
  check (module in ('care','members','events','finance','duty','inventory','reports','settings','audit'));
-- (No new grant rows: inventory/reports grants arrive with their content.)


-- ── (b) centre-scope columns on volunteers ───────────────────────────────────────────
alter table public.volunteers
  add column centre_id uuid references public.centres(id),
  add column scope text not null default 'own_center' check (scope in ('all_centers','own_center'));

-- Today's roles see across all centres. Care volunteers keep own_center + null centre
-- (inert — they hold no ERP grants). Backfilling centre_id from the free-text center
-- label is a SEPARATE later cleanup — deliberately not attempted here.
update public.volunteers
   set scope = 'all_centers'
 where role in ('admin', 'erp_admin', 'committee');


-- ── (c) centre_scope_allows(): may the CURRENT user see a row owned by p_centre_id? ──
-- SECURITY DEFINER so it can read volunteers on the caller's behalf. all_centers → true;
-- own_center → the row's centre must match the caller's centre_id; no session/inactive
-- → false. p_centre_id IS NULL means "not centre-owned" (only all_centers passes).
create or replace function public.centre_scope_allows(p_centre_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce(
    (
      select case
        when v.scope = 'all_centers' then true
        when v.scope = 'own_center'  then (p_centre_id is not null and v.centre_id = p_centre_id)
        else false
      end
      from public.volunteers v
      where v.id = auth.uid()
        and v.active = true
    ),
    false
  );
$$;

revoke all on function public.centre_scope_allows(uuid) from public;
grant execute on function public.centre_scope_allows(uuid) to authenticated;


-- ── (d) compose the scope dimension into the member-data policies ────────────────────
-- Every centre-owned read = module gate AND centre_scope_allows(<row's centre_id>).
-- centres / teams / audit_log are intentionally left module-gated only (reference data
-- and audit trail are not centre-owned).

drop policy if exists "members module can read members" on public.members;
create policy "members module can read members" on public.members
  for select to authenticated
  using (
    public.has_module_access('members','view')
    and public.centre_scope_allows(gyt_centre_id)
  );

drop policy if exists "members module can read member_teams" on public.member_teams;
create policy "members module can read member_teams" on public.member_teams
  for select to authenticated
  using (
    public.has_module_access('members','view')
    and exists (
      select 1 from public.members m
       where m.id = member_teams.member_id
         and public.centre_scope_allows(m.gyt_centre_id)
    )
  );

drop policy if exists "members module can read member_skills" on public.member_skills;
create policy "members module can read member_skills" on public.member_skills
  for select to authenticated
  using (
    public.has_module_access('members','view')
    and exists (
      select 1 from public.members m
       where m.id = member_skills.member_id
         and public.centre_scope_allows(m.gyt_centre_id)
    )
  );

-- Staging: an unmatched legacy row (member_id null) is HQ-domain (all_centers only);
-- a matched one follows its member's centre.
drop policy if exists "members module can read legacy_rows" on public.legacy_rows;
create policy "members module can read legacy_rows" on public.legacy_rows
  for select to authenticated
  using (
    public.has_module_access('members','view')
    and (
      public.centre_scope_allows(null)
      or exists (
        select 1 from public.members m
         where m.id = legacy_rows.member_id
           and public.centre_scope_allows(m.gyt_centre_id)
      )
    )
  );

-- Import batches are an HQ-only operational domain (all_centers scope only).
drop policy if exists "members module can read import_batches" on public.import_batches;
create policy "members module can read import_batches" on public.import_batches
  for select to authenticated
  using (
    public.has_module_access('members','view')
    and public.centre_scope_allows(null)
  );
