-- 020_finance_foundation.sql
-- =====================================================================================
-- PURPOSE (ERP Phase D, Step 1 — finance foundation).
--   The finance wing's data substrate: member fee pledges (per-member, varying), the
--   monthly fee-payment book (explicit month ranges + per-centre sequential receipt
--   numbers), a per-centre monthly collection-pause toggle, a centre expense ledger,
--   and the mutual-aid (互助金) fund entries. NO API routes and NO UI ship in this step
--   — this migration only lays the tables + module wiring the Phase D routes will use.
--
--   DESIGN ETHOS (charity 只求维持不求盈利 — approved in XLFM_Phase_D_Design_Mockup.html):
--     • NO automatic cap. Collection is governed by a MANUAL per-centre monthly PAUSE
--       toggle (centre_finance_months.collection_paused) + full transparency — never an
--       enforced ceiling.
--     • Pledges VARY per member and are OPTIONAL. fee_pledge_amount NULL = 未认捐 (has not
--       pledged). 豁免 (waived) is a FIRST-CLASS state via fee_waived_from — NOT a pledge
--       of 0, and never conflated with "hasn't pledged".
--     • Payments cover an EXPLICIT month range (months_from … months_to, first-of-month
--       dates). The covered range is stored, NEVER derived from amount ÷ pledge.
--     • Receipt numbers are a PER-CENTRE sequential book — UNIQUE (centre_id, receipt_no);
--       the app mints the next number per centre.
--     • NO "overdue" concept anywhere — no due-date column, no red/shaming state. A member
--       simply has, or has not, paid for a given month. Same guilt-free ethos as C3 (019).
--     • Corrections are VOIDs (voided_at/by/reason), never DELETEs. Deactivation/pause are
--       status columns. No row is ever physically removed.
--
--   SECURITY (identical to the rest of the platform):
--     • RLS ON for every new table; SELECT-only policies gated on
--         has_module_access('finance','view') AND centre_scope_allows(centre_id)
--       (mutual_aid_entries additionally passes fund-level rows where centre_id IS NULL).
--     • NO INSERT/UPDATE/DELETE policies anywhere — ALL writes go through service-role
--       routes (Phase D) that call writeAudit on every mutation.
--     • The new members fee columns are covered by the EXISTING members SELECT policy
--       (015: members:view AND centre_scope_allows(gyt_centre_id)) — no members policy is
--       touched here. (Open question for Ken: whether the finance roles below should also
--       hold a members grant so they can read the roster directly; deferred — the Phase D
--       finance routes read member pledges via service-role, bypassing RLS.)
--
--   MONTHLY 归集 IS MANUAL. The mutual-aid fund's monthly surplus collection is a manual
--   "归集" action that records mutual_aid_entries('in') rows — there is deliberately NO
--   cron / scheduled job anywhere in this design.
--
-- APPLY MANUALLY: paste into the Supabase SQL Editor (this repo applies migrations by
--   hand — there is no CLI runner). Run docs/erp/14-finance.md PREFLIGHT first; if it does
--   not match the stated expectation, STOP and reconcile before applying.
--
-- ROLLBACK (manual — safe, nothing external references these yet). Dropping a table drops
--   its RLS policies automatically. Reverse dependency order:
--     drop table if exists public.mutual_aid_entries;
--     drop table if exists public.expenses;
--     drop table if exists public.centre_finance_months;
--     drop table if exists public.fee_payments;
--     -- unseed the finance role bundles:
--     delete from public.role_grants where role in ('finance_director','centre_finance');
--     -- restore the pre-020 volunteers role CHECK (name will differ from the autogenerated
--     -- one; this restores the RULE):
--     alter table public.volunteers drop constraint if exists volunteers_role_check;
--     alter table public.volunteers add  constraint volunteers_role_check
--       check (role in ('admin','volunteer','erp_admin','committee'));
--     -- drop the members fee columns:
--     alter table public.members
--       drop column if exists fee_pledge_amount,
--       drop column if exists fee_pledge_period,
--       drop column if exists fee_waived_from,
--       drop column if exists fee_waiver_note;
-- =====================================================================================


-- ── (a) members: per-member fee pledge + first-class waiver state ─────────────────────
-- fee_pledge_amount NULL = 未认捐 (has not pledged). Waived is NOT a pledge of 0 — it is the
-- separate fee_waived_from date (+ optional note). A member may be waived while also holding
-- a historical pledge, so the two are independent columns, not one enum.
alter table public.members
  add column fee_pledge_amount numeric(10, 2)
    check (fee_pledge_amount is null or fee_pledge_amount > 0),   -- NULL = 未认捐; a pledge is always > 0
  add column fee_pledge_period text
    check (fee_pledge_period in ('month', 'year')),               -- NULL until pledged
  add column fee_waived_from date,                                -- NULL = not waived; first-class 豁免 state
  add column fee_waiver_note text;                                -- e.g. '理事会 2026-03 决议豁免'


-- ── (b) fee_payments — the monthly fee book (explicit month ranges, per-centre receipts) ─
-- One row per receipt. months_from/months_to are the FIRST OF each covered month and are
-- stored explicitly (a payment states WHICH months it covers) — never inferred from amount.
-- Corrections are voids, never deletes. receipt_no is a per-centre sequential book.
create table public.fee_payments (
  id uuid primary key default gen_random_uuid(),
  centre_id uuid not null references public.centres(id),
  member_id uuid not null references public.members(id),
  receipt_no text not null,                                       -- per-centre sequential; app-minted
  paid_at date not null,                                          -- when the money was received
  amount numeric(10, 2) not null check (amount > 0),
  months_from date not null
    check (extract(day from months_from) = 1),                    -- first-of-month invariant
  months_to date not null
    check (extract(day from months_to) = 1),                      -- first-of-month invariant
  constraint fee_payments_month_range check (months_to >= months_from),
  channel text not null check (channel in ('cash', 'bank_transfer', 'to_hq')),
  note text,
  entered_by uuid not null references public.volunteers(id),
  voided_at timestamptz,
  voided_by uuid references public.volunteers(id),
  void_reason text,
  created_at timestamptz not null default now(),
  constraint fee_payments_receipt_book unique (centre_id, receipt_no)
);

-- Coverage lookups ("has member X paid through month Y at centre Z?").
create index fee_payments_coverage_idx on public.fee_payments (centre_id, member_id, months_to);


-- ── (c) centre_finance_months — the MANUAL per-centre monthly pause toggle ────────────
-- A centre that has covered its needs for a month pauses collection for that month. This is
-- the transparency-and-pause model that REPLACES any automatic cap. One row per (centre, month).
create table public.centre_finance_months (
  centre_id uuid not null references public.centres(id),
  month date not null,                                            -- first-of-month
  collection_paused boolean not null default false,
  paused_note text,                                               -- why paused (transparency)
  updated_by uuid references public.volunteers(id),
  updated_at timestamptz not null default now(),
  primary key (centre_id, month),
  constraint centre_finance_months_first_of_month check (extract(day from month) = 1)
);


-- ── (d) expenses — per-centre expense ledger ─────────────────────────────────────────
-- Corrections are voids, never deletes. receipt_path points at a PRIVATE Storage bucket
-- (wired in a later Phase D step, exactly like C3's payment-proofs bucket — NULL for now).
create table public.expenses (
  id uuid primary key default gen_random_uuid(),
  centre_id uuid not null references public.centres(id),
  spent_at date not null,
  category text not null check (category in ('rent', 'utilities', 'maintenance', 'activity', 'misc')),
  description text not null,
  amount numeric(10, 2) not null check (amount > 0),
  receipt_path text,                                              -- private bucket object path (wired later)
  entered_by uuid not null references public.volunteers(id),
  voided_at timestamptz,
  voided_by uuid references public.volunteers(id),
  void_reason text,
  created_at timestamptz not null default now()
);

create index expenses_centre_date_idx on public.expenses (centre_id, spent_at);


-- ── (e) mutual_aid_entries — the 互助金 fund ledger ───────────────────────────────────
-- 'in'  = money flowing INTO the fund (per-centre 归集 surplus rows carry centre_id; other
--         fund-level income is centre_id NULL).
-- 'out' = disbursement — REQUIRES a 理事会 resolution number (resolution_no), enforced below.
-- centre_id NULL = fund-level (HQ) row; a non-null centre_id is a per-centre contribution.
-- The monthly 归集 that produces 'in' rows is a MANUAL action — no cron.
create table public.mutual_aid_entries (
  id uuid primary key default gen_random_uuid(),
  entry_type text not null check (entry_type in ('in', 'out')),
  amount numeric(10, 2) not null check (amount > 0),
  description text not null,
  resolution_no text,                                             -- required for 'out' (see CHECK)
  month date not null,
  centre_id uuid references public.centres(id),                   -- NULL = fund-level; else per-centre 'in'
  created_by uuid not null references public.volunteers(id),
  created_at timestamptz not null default now(),
  -- a disbursement ('out') must cite a resolution; 'in' rows need not.
  constraint mutual_aid_out_needs_resolution
    check (entry_type <> 'out' or resolution_no is not null)
);

create index mutual_aid_month_idx on public.mutual_aid_entries (month);


-- ── (f) RLS — enable + SELECT-only policies gated by finance grant + centre scope ─────
-- Writes stay service-role-only: NO INSERT/UPDATE/DELETE policies anywhere.
alter table public.fee_payments          enable row level security;
alter table public.centre_finance_months enable row level security;
alter table public.expenses              enable row level security;
alter table public.mutual_aid_entries    enable row level security;

-- Centre-owned finance tables: finance:view AND the row's centre is in the caller's scope.
create policy "finance module can read fee_payments" on public.fee_payments
  for select to authenticated
  using (
    public.has_module_access('finance', 'view')
    and public.centre_scope_allows(centre_id)
  );

create policy "finance module can read centre_finance_months" on public.centre_finance_months
  for select to authenticated
  using (
    public.has_module_access('finance', 'view')
    and public.centre_scope_allows(centre_id)
  );

create policy "finance module can read expenses" on public.expenses
  for select to authenticated
  using (
    public.has_module_access('finance', 'view')
    and public.centre_scope_allows(centre_id)
  );

-- Mutual-aid: fund-level rows (centre_id NULL) are visible to any finance:view holder whose
-- scope covers the fund (centre_scope_allows(NULL) is true only for all_centers); per-centre
-- rows follow the caller's centre scope.
create policy "finance module can read mutual_aid_entries" on public.mutual_aid_entries
  for select to authenticated
  using (
    public.has_module_access('finance', 'view')
    and (centre_id is null or public.centre_scope_allows(centre_id))
  );


-- ── (g) module wiring — future finance role bundles ──────────────────────────────────
-- admin + erp_admin ALREADY hold ('*','finance','admin') and committee holds
-- ('committee','finance','view') from 013 — nothing to add there. This step seeds the two
-- Phase D finance roles as free-text role bundles (role_grants has no FK / no CHECK on the
-- role column, so seeding unused roles is clean and inert until a volunteer holds the role):
--   finance_director (财务总监) — platform-wide finance control; paired with scope=all_centers.
--   centre_finance   (中心财政) — enters payments/expenses for own centre; scope=own_center.
-- NOTE: the all_centers / own_center dimension is a PER-VOLUNTEER setting (volunteers.scope,
-- from 015), applied when the account is created — it is NOT part of role_grants. These
-- bundles grant only the finance module (deliberately minimal); whether they also need a
-- members grant to read the roster is an open question deferred to Ken.
insert into public.role_grants (role, module, access) values
  ('finance_director', 'finance', 'admin'),
  ('centre_finance',   'finance', 'edit')
on conflict (role, module) do nothing;

-- Allow these two roles to actually be assigned to a volunteer. The 015 role CHECK is
-- named (volunteers_role_check); drop it dynamically (defensive — it may have been
-- auto-renamed by an earlier rollback/replay) and add the widened named replacement.
do $$
declare
  c_name text;
begin
  select conname
    into c_name
    from pg_constraint
   where conrelid = 'public.volunteers'::regclass
     and contype  = 'c'
     and pg_get_constraintdef(oid) ilike '%role%'
   limit 1;

  if c_name is not null then
    execute format('alter table public.volunteers drop constraint %I', c_name);
  end if;
end $$;

alter table public.volunteers
  add constraint volunteers_role_check
  check (role in ('admin', 'volunteer', 'erp_admin', 'committee', 'finance_director', 'centre_finance'));
